# Generated by Django 5.1 on 2024-08-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalImpactDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ozone_depletion', models.IntegerField(blank=True, null=True)),
                ('human_toxicity', models.IntegerField(blank=True, null=True)),
                ('eutrophication_marine_environments', models.IntegerField(blank=True, null=True)),
                ('ecotoxicity', models.IntegerField(blank=True, null=True)),
                ('resouce_use', models.IntegerField(blank=True, null=True)),
                ('particulate_matter', models.IntegerField(blank=True, null=True)),
                ('eutrophication_freshswater', models.IntegerField(blank=True, null=True)),
                ('photochemical_ozone_formation', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
